### ISSUE TITLE
Unable to tap menu button when set to .normal/.slideAside

### ISSUE THREAD

**Issue by xergic** [itisnajim/NSideMenu#1]
First of all, thanks for this great component, saved me a lot of time!

I've encountered a problem when `style` is set to `.normal` or `.slideAside` - I'm unable to tap a button in navigationBar to open the menu again. It works fine with `.slideAbove`.

I'm using Xcode 13.2 and iOS 15.2.

### How to reproduce
1. Use [Example app](https://github.com/itisnajim/NSideMenuApp)
2. Run in Simulator
3. Change style to `normal` or `slideAside` (in the app menu)
4. Close the menu (tap X)
5. You're not able to tap button to open the menu again

I guess it could be some layer covering half of the view? Let me know if you need anything to debug (video?), I'm happy to help!

**Comment by xergic** [comment]
Update: seems to be connected to [this line](https://github.com/itisnajim/NSideMenu/blob/main/Sources/NSideMenu/NSideMenuView.swift#L95). If the `.cornerRadius` modifier is removed, it works as expected. Making this modifier conditional should probably fix it.

Using something like this [source](https://www.avanderlee.com/swiftui/conditional-view-modifier/):
```swift
extension View {
    /// Applies the given transform if the given condition evaluates to `true`.
    /// - Parameters:
    ///   - condition: The condition to evaluate.
    ///   - transform: The transform to apply to the source `View`.
    /// - Returns: Either the original `View` or the modified `View` if the condition is `true`.
    @ViewBuilder func `if`<Content: View>(_ condition: Bool, transform: (Self) -> Content) -> some View {
        if condition {
            transform(self)
        } else {
            self
        }
    }
}
```

And then:
```swift
main
    .if((options.show && (options.style == .scale || options.style == .rotate)), transform: { view in
        view.cornerRadius(options.cornerRaduisIfNeeded)
    })
```

**Comment by itisnajim** [comment]
Oh, so you managed to fix that, thanks for the contribution, I'm here if anything is needed 😄
